### ISSUE TITLE
error using vite

### ISSUE THREAD

**Issue by erwinstone** [taufik-nurrohman/color-picker#76]
got error using vite:

```
Uncaught TypeError: Cannot destructure property 'hooks' of '$2' as it is undefined.
```

Demo:
https://stackblitz.com/edit/vitejs-vite-e4xyev?file=src%2FApp.jsx

**Comment by taufik-nurrohman** [comment]
It may be caused by [@taufik-nurrohman/hook](https://github.com/taufik-nurrohman/hook) dependency that was not set to a fixed version. It was updated some times ago to make it attached to the `Function.prototype` instead of the `Function` instance.

https://github.com/taufik-nurrohman/hook/compare/v1.0.2...v1.0.4

I will consider updating this application but the name will likely be renamed to `ColorPicker` as I am also already renamed [@taufik-nurrohman/text-editor](https://github.com/taufik-nurrohman/text-editor) function name which was `TE`, to `TextEditor`.

**Comment by taufik-nurrohman** [comment]
Could you, for now import the compiled application as if it is a local file like this maybe, before I am updating the application dependencies.

~~~ js
const CP = require('../node_modules/@taufik-nurrohman/color-picker/index.js').default;
~~~

**Comment by taufik-nurrohman** [comment]
Ummm, should not work because it bounds to `window`.

**Comment by taufik-nurrohman** [comment]
Downgrade the hook dependency `npm install @taufik-nurrohman/hook@1.0.2 --save --save-exact`

**Comment by erwinstone** [comment]
Downgrading the hook dependency eliminates the error, but the color-picker does not appear.
Checkout the updated demo: https://stackblitz.com/edit/vitejs-vite-3h9ddu?file=package.json

**Comment by taufik-nurrohman** [comment]
@erwinstone It&rsquo;s there. You just need to include the CSS file manually.

![Screenshot 2024-03-17 144634](https://github.com/taufik-nurrohman/color-picker/assets/1669261/8051b60b-ef7e-41be-b69e-87eaf1c38738)

**Comment by erwinstone** [comment]
Got it !
It works now, thank you
